# fly.toml app configuration file generated for exercise-tracker on 2024-12-07T12:48:41-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'exercise-tracker'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
