# fly.toml app configuration file generated for exercise-tracker on 2024-12-07T12:48:41-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'exercise-tracker'
primary_region = 'sea'
swap_size_mb = 256

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[deploy]
  release_command = "bun run migration:run"

[env]
  BASE_URL = "https://set.luketurner.org"

[metrics]
port = 3001
path = "/metrics" # default for most prometheus exporters
